title: Sara Rostami

collections:
  publications:
     output: true
  projects:
     output: true
  
author:
  name: SaraRostami
  email: sararostami.d98@gmail.com
description: Personal website of Sara Rostami

show_excerpts: true

minima:
  date_format: "%b %-d, %Y"


theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
